server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: common-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:

management:
  endpoints:
    web:
      exposure:
        include: "*"
