###
GET http://localhost:8080/api/hello

###
POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=normal-app&client_secret=123456&username=18969553171&password=123456

###
GET http://localhost:8080/api/hello
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTExNzE5MDcsInVzZXJfbmFtZSI6IjE4OTY5NTUzMTcxIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiI0ODM2MzQ3NS0wYzcyLTQ4MWItOGY0Ny04YjM2YTEwMDI0YzUiLCJjbGllbnRfaWQiOiJub3JtYWwtYXBwIiwic2NvcGUiOlsiU0NPUEVfVFJVU1QiXX0.OTHk2auobYGi84yRUB244Fjt2bg0Ak5NpHRLFEhy6DIDS_Ml4sbsWpkaLBF1Yo_KtEFQbk569Xd-xRzHuZ0PQYnBQZ42shiGRhDrY2K-h65JTuKnlQbhiv20-wClUIhI1vQtoE-e5grk5xcS5gI-CQFw8JZ5vSdU2gt_bAtiXxw

###
POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxODk2OTU1MzE3MSIsInNjb3BlIjpbIlNDT1BFX1RSVVNUIl0sImF0aSI6IjMxNTk1M2RlLTQzOTktNDg4ZC1hZDhlLTY1NzNjMzZkODRhZSIsImV4cCI6MTU5MTI1NDIxNCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiI2OGQ0YzJlMi0zMThjLTRkZmYtODIzYi05ZGJiMTY2NmM0ZGEiLCJjbGllbnRfaWQiOiJub3JtYWwtYXBwIn0.bigWtjanNMJ_ZL-h3FKCqTBMTyngtafbishg6dnV1wl6CNSZmMYjbiM6msCedzfZ1XSq4Kidw3wcjmkvzygFWJcUPuwrNsg1Sa-lapQrcpudd0lQSAEvRslm27ZvFfOzPZmZhrLVF3FlBd_QTBEAHbUwWolrxVhouGu_pxZBpRA&client_id=normal-app&client_secret=123456

###