###
GET http://localhost:8080/api/hello

###
POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=normal-app&client_secret=123456&username=18969553171&password=123456

###
GET http://localhost:8080/api/hello
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTE4Nzk2MTksInVzZXJfbmFtZSI6IjE4OTY5NTUzMTcxIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiIwZTQ3MmFkYy00ODRhLTQzMDAtOTJkMi1lNWI5ZjdmOTU1NzMiLCJjbGllbnRfaWQiOiJub3JtYWwtYXBwIiwic2NvcGUiOlsiU0NPUEVfVFJVU1QiXX0.Y3pGNF1xyRItmRIoQCN32evE1DoxFf2R79-d6W_XNB9LCS0Sr6uNKdp9b0h_dkBWtejsBRuDeRPa7YgvBg6MS5FZdxcH9GnDXFDhcKFJR-rTol3Hi5-8jailVPTrVzGJpLh8L4Py9GdQaZQOeqRNXBK5BwP-22OhOZr-rSVb5-4

###
POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxODk2OTU1MzE3MSIsInNjb3BlIjpbIlNDT1BFX1RSVVNUIl0sImF0aSI6IjMxNTk1M2RlLTQzOTktNDg4ZC1hZDhlLTY1NzNjMzZkODRhZSIsImV4cCI6MTU5MTI1NDIxNCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiI2OGQ0YzJlMi0zMThjLTRkZmYtODIzYi05ZGJiMTY2NmM0ZGEiLCJjbGllbnRfaWQiOiJub3JtYWwtYXBwIn0.bigWtjanNMJ_ZL-h3FKCqTBMTyngtafbishg6dnV1wl6CNSZmMYjbiM6msCedzfZ1XSq4Kidw3wcjmkvzygFWJcUPuwrNsg1Sa-lapQrcpudd0lQSAEvRslm27ZvFfOzPZmZhrLVF3FlBd_QTBEAHbUwWolrxVhouGu_pxZBpRA&client_id=normal-app&client_secret=123456

###