server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
    gateway:
      routes:
        - id: api-service-route
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://127.0.0.1:8081/.well-known/jwks.json'

management:
  endpoints:
    web:
      exposure:
        include: "*"
